# Generated by Django 4.0 on 2022-02-13 05:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_no', models.IntegerField()),
                ('departure_time', models.TimeField(default=datetime.time)),
                ('destinations', models.TextField(choices=[('1', 'Villupuram'), ('2', 'Chengalpattu'), ('3', 'Chennai')])),
                ('seats_available', models.IntegerField()),
                ('ticket_costs', models.IntegerField(choices=[('1', '100'), ('2', '150'), ('3', '200')])),
            ],
        ),
    ]
