# Generated by Django 4.0 on 2022-02-13 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busapp', '0002_alter_busdetails_destinations_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busdetails',
            name='ticket_costs',
            field=models.IntegerField(choices=[(1, 100), (2, 150), (3, 200)], default='3'),
        ),
    ]
