# Generated by Django 4.0 on 2022-02-13 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busapp', '0003_alter_busdetails_ticket_costs'),
    ]

    operations = [
        migrations.AddField(
            model_name='busdetails',
            name='persons',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
