# Generated by Django 4.0 on 2022-02-13 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busapp', '0004_busdetails_persons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busdetails',
            name='ticket_costs',
            field=models.IntegerField(choices=[(100, 1), (150, 2), (200, 3)], default=200),
        ),
    ]
