# Generated by Django 4.0 on 2022-02-13 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busapp', '0005_alter_busdetails_ticket_costs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busdetails',
            name='destinations',
            field=models.TextField(choices=[('Villupuram', '1'), ('Chengalpattu', '2'), ('Chennai', '3')], default='3'),
        ),
    ]
