# Generated by Django 4.0 on 2022-02-13 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busapp', '0007_remove_busdetails_persons_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busdetails',
            name='destinations',
            field=models.IntegerField(choices=[(0, 'Villupuram'), (1, 'Chengalpattu'), (2, 'Chennai')], default=2),
        ),
    ]
