# Generated by Django 4.0 on 2022-02-13 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busapp', '0008_alter_busdetails_destinations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busdetails',
            name='destinations',
            field=models.IntegerField(choices=[('Villupuram', 'Villupuram'), ('Chengalpattu', 'Chengalpattu'), ('Chennai', 'Chennai')], default='Chennai'),
        ),
        migrations.AlterField(
            model_name='busdetails',
            name='ticket_costs',
            field=models.IntegerField(choices=[(100, 100), (150, 150), (200, 200)], default=200),
        ),
    ]
